# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Test the framework"
  lane :test do
    spm(command: "test")
  end

  desc "Lint the framework"
  lane :lint do
    swiftlint(
      mode: :lint,
      raise_if_swiftlint_error: true,
      ignore_exit_status: false 
    )
  end

end
